project:
  type: website

website:
  image: images/ohmeow_logo.png
  favicon: images/ohmeow_favicon.png
  site-url: "https://ohmeow.com"
  description: "ohmeow"
  twitter-card: true
  open-graph: true
  comments:
    utterances:
      repo: ohmeow/ohmeow_website
  navbar:
    logo: images/ohmeow_logo.png
    logo-alt: ohmeow.com
    pinned: true
    collapse-below: lg
    left:
      - text: Guides
        icon: tools
        menu:
          - text: "Vue3"
            icon: box-arrow-up-right
            href: pages/guides/vue3-guide.md
          - text: "Fast API"
            icon: box-arrow-up-right
            href: pages/guides/fastapi-guide.md
          - text: "PostgreSQL"
            icon: box-arrow-up-right
            href: pages/guides/postgresql-guide.md
          - text: "Deployment"
            icon: box-arrow-up-right
            href: pages/guides/deployment-guide.md
      - text: Projects
        icon: stack
        menu:
          - text: "blurr"
            icon: layers
            href: https://ohmeow.github.io/blurr/
      - text: Study Groups
        icon: book
        menu:
          - text: "fastai x Hugging Face Study Group"
            icon: youtube
            href: https://www.youtube.com/playlist?list=PLD80i8An1OEF8UOb9N9uSoidOGIMKW96t
      - href: about.qmd
        icon: person-circle

    right:
      - icon: twitter
        href: https://twitter.com/waydegilliam
      - icon: github
        href: https://github.com/ohmeow
      - icon: rss
        href: https://ohmeow.com/index.xml

format:
  html:
    theme:
      - darkly
      - custom.scss
    page-layout: full
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/?(www)\.ohmeow\.com\/**'
