project:
  type: website

website:
  image: images/ohmeow_logo.png
  favicon: images/ohmeow_favicon.png
  site-url: "https://ohmeow.com"
  description: "ohmeow"
  twitter-card: true
  open-graph: true
  comments:
    utterances:
      repo: ohmeow/ohmeow_website
  navbar:
    logo: images/ohmeow_logo.png
    logo-alt: ohmeow.com
    pinned: true
    collapse-below: lg
    left:
      - text: Guides
        menu:
          - text: "Vue3"
            icon: app
            href: pages/guides/vue3-guide.md
          - text: "Fast API"
            icon: app
            href: pages/guides/fastapi-guide.md
          - text: "PostgreSQL"
            icon: app
            href: pages/guides/postgresql-guide.md
          - text: "Deployment"
            icon: app
            href: pages/guides/deployment-guide.md
      - text: Projects
        menu:
          - text: "blurr"
            icon: app
            href: https://ohmeow.github.io/blurr/
      - text: Study Groups
        menu:
          - text: "fastai x Hugging Face Study Group"
            icon: book
            href: https://www.youtube.com/playlist?list=PLD80i8An1OEF8UOb9N9uSoidOGIMKW96t
      - href: about.qmd

    right:
      - icon: twitter
        href: https://twitter.com/waydegilliam
      - icon: github
        href: https://github.com/ohmeow

format:
  html:
    theme:
      - darkly
      - custom.scss
    page-layout: full
